### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by ixjlyons** [JelteF/PyLaTeX#104]
I think one thing that is lacking from the current documentation is explicit description of the mapping between PyLaTeX classes and the resulting LaTeX output.

A natural mechanism for describing this mapping would be through tutorials. A tutorial could start out with a "target" tex file and break it down bit by bit, showing a part of the tex file and then describing how that output is achieved with PyLaTeX. A basic tutorial would go through things like sections, math, figures, etc. A more advanced tutorial could introduce custom commands/environments/containers. The latter would be especially helpful.

I wouldn't mind working on this, but I can't really discuss reasoning behind design decisions (which is another thing tutorials facilitate nicely). That can always be added later, of course.

**Comment by JelteF** [comment]
This sounds interesting, but I feel like the examples already do something like this. Would it maybe be enough to just show the final `tex` file as well and not just the pdf?
