### ISSUE TITLE
How to build table of content?

### ISSUE THREAD

**Issue by imadcat** [JelteF/PyLaTeX#105]
Even when explicitly called twice in the program it will still not build table of content

```
latex.generate_pdf(report_name, clean=False,
                           compiler='xelatex -interaction=nonstopmode -output-directory=' +
                                    upload_folder_report_pdf)
latex.generate_pdf(report_name, clean=True,
                           compiler='xelatex -interaction=nonstopmode -output-directory=' +
                                    upload_folder_report_pdf)
```

Could generate_pdf method support running compiler multiple times intrinsically?

**Comment by JelteF** [comment]
Try running using the extra_compiler_args flag and pass it `--xelatex`.
That way latexmk will be used with xelatex. Latexmk runs the compiler as
often as needed.

**Comment by JelteF** [comment]
Is this fixed for you now?

**Comment by imadcat** [comment]
Following the suggestion i was able to generate PDF with ToC as:
```latex.generate_pdf(report_name, clean=True,
                           compiler = 'latexmk -f -xelatex -interaction=nonstopmode -output-directory=' +
                           upload_folder_report_pdf)```

Thank you @JelteF

**Comment by imadcat** [comment]
A non related question:

[On pylatex's page at sourceforge](http://pylatex.sourceforge.net) it says that 
>The pyLaTeX project is no longer being developed. However, there is a new project in its place that is built from the same ideas and standpoints that is much more mature and complete. Please visit the plasTeX project.

But clearly pylatex is actively developed by you here,
What's the relationship between pylatex and this plasTeX?

**Comment by JelteF** [comment]
It's an entirely unrelated package. As far as I can tell it also has a quite different goald than this package. It is a bit similar to pandoc in that it parses latex and generates other formats, but much less suported formats. Because it was renamed and it was not in pip it didn't seem like much confusion could ensue.

**Comment by imadcat** [comment]
and are you going to push the version 1.0 into the PyPi repo?

**Comment by JelteF** [comment]
It's already there:
https://pypi.python.org/pypi/PyLaTeX/1.0.0

**Comment by imadcat** [comment]
Great! Is version 1.0 backward compatible with the previous version 0.8?

**Comment by JelteF** [comment]
Nope, the stuff has been moved around to let the API make more sense and
all strings are escaped by default. See the changelog in the documentation
for more details.

**Comment by Mascha16** [comment]
Hello, 
I'm using pylatex to create a PDF, and i need to know how to generate a table of contents. 
Can you please help me ? 
Thank you !

**Comment by DanielWarfield1** [comment]
From what I can tell, PyLaTeX simply generates a .tex file for a .tex interpreter to deal with. So, if you can inject LaTeX commands directly, you're in business. 

Luckily, it seems like you can. This does the trick:

```
from pylatex.utils import NoEscape
doc.append(NoEscape('\\tableofcontents'))
```
