### ISSUE TITLE
`lmodern=False` causes pdflatex to fail

### ISSUE THREAD

**Issue by rotton** [JelteF/PyLaTeX#111]
When using `lmodern=False` as an option for the `Document` class, PyLaTeX writes the word 'False' into the preamble of the `.tex` file, causing `pdflatex` to fail. Actually, this option should do nothing, since it means I do not want to use Latin Modern, but Computer Modern or another font which I would specify in the preamble.
[mweBugPyLaTeX.txt](https://github.com/JelteF/PyLaTeX/files/89107/mweBugPyLaTeX.txt)
Just rename the attached example to `*.py` and execution should succeed. Now, if you set `raiseError = True` in line 15, interpreter throws an error.

**Comment by JelteF** [comment]
The commit I just pushed should fix this issue.
