### ISSUE TITLE
import Document error on OSX

### ISSUE THREAD

**Issue by ClintfromCanada** [JelteF/PyLaTeX#118]
Hello there, I am a noob at this and python, however I have scoured the net for enlightenment can cannot find anything that will help.

I have brew installed python 2.7 and 3, default is 2.7
I have pip installed pylatex

When I try and run your example app, I get this error:
"ImportError: cannot import name Document".
If I remove Document, it cannot import Section, etc, so something is not working as far as being able to see pylatex? But I don't get "no module named ..."

For the life of me I cannot figure out how to correct this error or even how to troubleshoot that it is anything simpler?  Could somehow python not be seeing pylatex somehow?

Thanks,

Clint

**Comment by JelteF** [comment]
That sounds like the module is not installed for the python version that you are running. 

Could you show the output of the following commands: 

```
pip --version
python --version
pip install pylatex
```

**Comment by Clintbaker** [comment]
Thank you Jelte for the response!i am out of town this week but will try it
as soon as I return.  Much appreciated!

Clint

**Comment by Clintbaker** [comment]
Here is my response from the terminal.  Does this give any hint?

Thanks,
Clint

Clints-iMac:Downloads clintbaker$ pip --version

pip 8.1.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

Clints-iMac:Downloads clintbaker$ python --version

Python 2.7.11

Clints-iMac:Downloads clintbaker$ pip install pylatex

Requirement already satisfied (use --upgrade to upgrade): pylatex in
/usr/local/lib/python2.7/site-packages

Requirement already satisfied (use --upgrade to upgrade): future in
/usr/local/lib/python2.7/site-packages (from pylatex)

Requirement already satisfied (use --upgrade to upgrade): ordered-set in
/usr/local/lib/python2.7/site-packages (from pylatex)

Clints-iMac:Downloads clintbaker$

**Comment by JelteF** [comment]
Sorry, I forgot about this. 
Have you already found the issue? 
Otherwise could you post the code that you are trying to run, because your output seems quite alright?

**Comment by JelteF** [comment]
I'm closing this until more info is available.
