### ISSUE TITLE
3to2 issues on Windows

### ISSUE THREAD

**Issue by raoufhamouda** [JelteF/PyLaTeX#119]
Hello there!

When converting latex_object.py using ``3to2``, there is a difference between the converted file and the one preinstalled using ``pip install pylatex`` (python 2.7 config).

3to2 conversion leads to (then the error ImportError: cannot import name recursive_repr raises):

``from __future__ import with_statement``
``from __future__ import absolute_import``
``from ordered_set import OrderedSet``
``from ..utils import dumps_list``
``from abc import abstractmethod, ABCMeta``
``from reprlib import recursive_repr``
``from inspect import getargspec``
``from itertools import imap``
``from io import open``

whereas the preinstalled version contains (no ImportError raises):
``from __future__ import with_statement``
``from __future__ import absolute_import``
``from __future__ import unicode_literals``
``from __future__ import print_function``
``from __future__ import division``
``from builtins import super``
``from builtins import open``
``from future import standard_library``
``standard_library.install_aliases()``
``from ordered_set import OrderedSet``
``from ..utils import dumps_list``
``from abc import abstractmethod, ABCMeta``
``from reprlib import recursive_repr``
``from inspect import getargspec``
``from itertools import imap``
``from io import open``

Is it a problem related to ``3to2`` module version?

Thanks so much for your help.

Cheers,

**Comment by JelteF** [comment]
To convert to python2 compatible code this script in the repo is used: https://github.com/JelteF/PyLaTeX/blob/master/convert_to_py2.sh

You could use that to convert the python3 source and it should work. It uses both `3to2` and `pasteurize` from the future library.

You might also be able to simply use `pip2 install .`, as it should be called when installing for python2 and no sources are available (such as when installing from the git url).

**Comment by raoufhamouda** [comment]
Hi,

Thanks for your comprehensive answer!

The point is that on windows 7, when installing 3to2, there isn't a 3to2.exe file created but a file 3to2 without extension, that represents a python script. [Then a renaming 3to2 -> 3te2.py is required to execute this script aiming at converting to python compatible code](http://stackoverflow.com/questions/14804287/running-py3to2-using-windows-7). The convert_to_py2.sh script can not be used then.

Is PyLatex developed for Posix environment only?

Regards,
Raouf.

**Comment by JelteF** [comment]
The library itself tries not to be Posix only, but as I only develop it on Linux some platform dependent bugs might be in it. 

The development setup is definitely Posix only though as I only develop it there. If you can create a windows compatible way of running the same commands as the convert_to_py2.sh script I have no problem merging it in though.

You can also install the current stable version of the library by simply using:
```bash
pip install pylatex
```
This should not require 3to2 as the converted Python2.7 files should be included in the package already.

**Comment by raoufhamouda** [comment]
OK I'll to do that.

I have noticed a dependent environment bug in converting file paths. Thanks for the merge ;) 

Cheers,
Raouf.

PS. Sorry for having developed on master branch by the way, I'll create dev branches from now on...

**Comment by JelteF** [comment]
I'm closing this. If this is still an issue, please reopen.
