### ISSUE TITLE
newcolumntype for tables

### ISSUE THREAD

**Issue by kriete** [JelteF/PyLaTeX#121]
Hey, I am currently using pylatex v1.0.0 and tried to use a custom columntype for the tabular environment.

So I appended the package array and added to the preamble the command for the newcolumntype. Generating (or dumping) the tex until this point looks good.
However, I create a Tabular environment with these custom columns and it throws me a TableRowSizeError since the table width is stated as 0.

A short code demo:
```
from pylatex import Document, Package, Tabular, NoEscape
doc = Document('customTable')
doc.packages.append(Package('geometry', options=['left=2cm', 'right=2cm']))
doc.packages.append(Package('array'))
doc.preamble.append(NoEscape(r'\newcolumntype{P}[1]{>{\centering\arraybackslash}p{#1}}'))

#standard columns
with doc.create(Tabular('|ccc|', pos='htb')) as table:
    table.add_hline()
    table.add_row(('Hello.', 'Hello, I am.', 'Hello, I am input.'))
    table.add_hline()
    table.add_row(('Hello.', 'Hello, I am.', 'Hello, I am input.'))
    table.add_hline()
    table.add_row(('Hello.', 'Hello, I am.', 'Hello, I am input.'))
    table.add_hline()

    
print doc.dumps()    

#custom columns
with doc.create(Tabular('|P{2cm} P{3cm} P{4cm}|', pos='htb')) as table:
    table.add_hline()
    table.add_row(('Hello.', 'Hello, I am.', 'Hello, I am input.'))
    table.add_hline()
    table.add_row(('Hello.', 'Hello, I am.', 'Hello, I am input.'))
    table.add_hline()
    table.add_row(('Hello.', 'Hello, I am.', 'Hello, I am input.'))
    table.add_hline()


doc.generate_pdf()
```
TableRowSizeError: Number of cells added to table (3) did not match table width (0)

Adding NoEscape to the tabular definition doesn't work too. Maybe you know where this problem is coming from?

Thanks and regards,

Edit: I am using python 2.7

**Comment by JelteF** [comment]
The problem is that the `_get_table_width` function does not support your custom column type:
https://github.com/JelteF/PyLaTeX/blob/master/pylatex/table.py#L19
There's three options to fix this.
1. Edit this function to recognize capital letters as well.
2. Set the `width` attribute on the tabular after initialization, to override the width calculated by `_get_table_width`. 
3. Use the `strict=False` keyword argument of the `add_row` method. This will allow you to add rows even if the cell count is not the same as the width.

**Comment by kriete** [comment]
Hello Jelte,

I used your third solution to set `strict=False`. This disables the check for equal number of (defined) cells as you've said and the output PDF seems to be correctly now.
Thank you for the explanation!

Kind regards,
