### ISSUE TITLE
Remove space between two append

### ISSUE THREAD

**Issue by Huade** [JelteF/PyLaTeX#122]
Hi,

There is a space between two `append`. For example, there is a space between `foo` and `bar` if we produce a pdf with the following code. Is there any way to get rid of it?

```python
from pylatex import Document, Section, Subsection, Command
from pylatex.utils import italic, NoEscape
doc = Document('basic')
with doc.create(Section('A section')):
        doc.append('foo')
        doc.append('bar')
doc.generate_pdf()
```

**Comment by JelteF** [comment]
You can set the `content_seperator` attribute to something else than a newline after initializing the section.
https://github.com/JelteF/PyLaTeX/blob/master/pylatex/base_classes/containers.py#L26

**Comment by Huade** [comment]
Thank you!
