### ISSUE TITLE
Increasing font size of whole document (using extsizes)

### ISSUE THREAD

**Issue by LydiaF** [JelteF/PyLaTeX#124]
Hi!

Firstly thank you so much for the package, it is going to be massively useful.

I need to increase the font size of the documents. To do this I am trying to use extsizes package (but do not have to use this one). 

In my python script I have:
    doc = Document(documentclass='extarticle')
    doc.packages.append(Package('extsizes'))

This gets us to this in latex:
\documentclass{extarticle}
\usepackage{extsizes}

However, I need it to print:
\documentclass[17pt]{extarticle}
\usepackage{extsizes}

Is there any (simple) way to do this? (I am not a programmer, hanging in here with my fingertips!)

Thank you very much,

Lydia

**Comment by JelteF** [comment]
Instead of using the `'extarticle'` string as documentclass you could use a `Command`. 
See the example for `Command`, it does basically exactly what you want: https://jeltef.github.io/PyLaTeX/current/pylatex/pylatex.base_classes.command.html?highlight=command#pylatex.base_classes.command.Command

**Comment by JelteF** [comment]
I'm closing this as this is probably not an issue. Please reopen if it persists.

**Comment by LydiaF** [comment]
Thank you, sorted :)
