### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by jimsrc** [JelteF/PyLaTeX#125]
Hello,
I just want to report an error that can easily be fixed.

I just installed this with:
```
pip install pylatex
```

but when I do:
```
import pylatex
```
I got:
```
ImportError: No module named builtins
```

Next thing do, is:
```
pip install future --upgrade
```
And now ```pylatex``` work OK! :-)

# More info of my system: 
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.1.0
  conda-build version : 1.8.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/jim/anaconda  (writable)
  default environment : /home/jim/anaconda
     envs directories : /home/jim/anaconda/envs
        package cache : /home/jim/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/r/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/jim/.condarc
    is foreign system : False

**Comment by JelteF** [comment]
Hmmm, #119 is probably related to this.

**Comment by JelteF** [comment]
What version of python is this for?

**Comment by jimsrc** [comment]
I just updated my issue: I have python v2.7

**Comment by JelteF** [comment]
All I can think of that could be the problem is that you already had a version of the future library, but an older one. Can you confirm this is the case? 
If so I could simply add a version to the dependency.

**Comment by jimsrc** [comment]
Hi,
Yes, I already a future installed.

**Comment by jimsrc** [comment]
Yes, I already had a future versión installed.

**Comment by JelteF** [comment]
Alright, then. I'll update the setup.py dependencies te depend on the newest version.
