### ISSUE TITLE
How can I plot a time series with PyLaTeX?

### ISSUE THREAD

**Issue by nelson2005** [JelteF/PyLaTeX#127]
First of all, thanks for a really cool library!

I'm trying to plot date series, like in this example

http://tex.stackexchange.com/questions/9733/pgfplot-datafile-format-for-datetime-field

but having a little trouble.  I think the difficulty is the lack of a usepgfplotslibrary macro in the LaTex output.  I can work around it using Command, but I was wondering if there was a better way.

Hints welcome!

**Comment by JelteF** [comment]
I don't use the pgfplot functionality in PyLaTeX myself, so it could very well be that some stuff can not be done with it easily.

What should work is to create a new class that subclasses `Plot` something like this:
```
DatePlot(Plot):
    packages = ['\usepgfplotslibrary{dateplot}']
```

If this indeed works it would be nice if you could make a pull request with the new class an example.

**Comment by nelson2005** [comment]
thanks for the tip, I'll give it a try!  I don't know how to use git, but I can let you know how it turns out.

**Comment by JelteF** [comment]
Any updates on this?

**Comment by nelson2005** [comment]
Not yet, sorry.  I'm new to Python and have a lot of things I need to get working, including this one.
On Aug 23, 2016 7:37 AM, Jelte Fennema <notifications@github.com> wrote:Any updates on this?

**Comment by JelteF** [comment]
I'm closing this as I'm not planning to add this myself. If you ever have time to make the pull request I'd be happy to merge it.

**Comment by nelson2005** [comment]
Fair enough, if I get back to that and get it working I'll share it with you.On Jan 12, 2017 4:25 PM, Jelte Fennema <notifications@github.com> wrote:I'm closing this as I'm not planning to add this myself. If you ever have time to make the pull request I'd be happy to merge it.
