### ISSUE TITLE
How to add symbol in table cell

### ISSUE THREAD

**Issue by johnerlandsson** [JelteF/PyLaTeX#130]
Say I want a cell in a table to read 10 &Omega;/km

I have this table

    value = u'10'
    gp_table = Tabular('l l')
    gp_table.add_row([bold('Resistans:'), value])

How do I append a command like \Omega to the value string?

I received a lot of weird errors when simply concatenating value + u'\u2126' and am therefor trying the latex way.

**Comment by JelteF** [comment]
The easiest way is to do it like this:

```python
value = u'10'
value = NoEscape(value + u' \Omega/km')

```
(Keep in mind that if the value is provided by a user you should escape it befor wrapping it in the `NoEscape` object, https://jeltef.github.io/PyLaTeX/latest/pylatex/pylatex.utils.html#pylatex.utils.escape_latex)

However, it  might be better in your case to use the "siunitx" Latex package for this in your case. This is also used in the quantities submodule of Pylatex so maybe that might be useful to use although I'm not sure if it supports resistance. https://jeltef.github.io/PyLaTeX/latest/pylatex/pylatex.quantities.html

**Comment by JelteF** [comment]
Hmmm, sad to hear that it didn't work. 

I'm looking into it right now. The kilometer thing is clear from the code that that does not work as it simply uses the name of the Unit and makes that a command. 
I thought of a simple fix for that simply checks if it starts with one of the prefixes defined in the quantities package and strips that and makes it its own command.
https://github.com/python-quantities/python-quantities/blob/master/quantities/units/prefixes.py 

The options argument is working just fine for me though. 
Could you try installing the github version and see if that fixes it?
```
pip install git+https://github.com/JelteF/PyLaTeX.git
```

**Comment by JelteF** [comment]
I see now that in the changelog that the options argument was indeed only added in the currently unreleased version:
https://jeltef.github.io/PyLaTeX/latest/changelog.html#added

I also just pushed the fix for the kilometer bug. Could you let me know if it works and close the issue it it does?

**Comment by johnerlandsson** [comment]
Works like a charm now. Thank you!
