### ISSUE TITLE
Figures get mixed with text

### ISSUE THREAD

**Issue by michalstepniewski** [JelteF/PyLaTeX#141]
Hello,

I am new to PyLatex and need to make a report real quick. I have made code and the problem is that figures get mixed with text. How do I anchor figures as sign so they do not get mixed with text?

Cheers,

Michal

**Comment by JelteF** [comment]
I'm sorry for responding so late, I think I missed this initially. However, I'm not sure what you mean with your question.  I will close this for now. If you can explain a bit better what behaviour you're having and what you require please reopen this issue.
