### ISSUE TITLE
PageStyle does not exist; can't run complex_report.py

### ISSUE THREAD

**Issue by adamhayes** [JelteF/PyLaTeX#143]
complex_report.py ( https://github.com/JelteF/PyLaTeX/blob/master/examples/complex_report.py ) throws exception 

`ImportError: cannot import name PageStyle`

PageStyle appears to have been removed from the PyLaTex module.

**Comment by JelteF** [comment]
That feature is not yet released. Please use the git version if you need it.

**Comment by adamhayes** [comment]
My mistake.  I shouldn't mix my apt install and the bleeding edge.
