### ISSUE TITLE
Make Preambule

### ISSUE THREAD

**Issue by nesergen** [JelteF/PyLaTeX#146]
I need to create preambule like this " \renewcommand{\sfdefault}{cmss} ".
The problem that it has two arguments and no options.
If I write python command : 
`doc.preamble.append(com.Command('renewcommand', NoEscape(u'\sfdefault'), 'cmss'))`
 
then receive : 
`\renewcommand[cmss]{\sfdefault}`
it is not the same as I need

**Comment by JelteF** [comment]
You can use a list of arguments for that

**Comment by nesergen** [comment]
You right, thanks !

Python script must be written like this:
`doc.preamble.append(Command('renewcommand', arguments = (NoEscape(u'\sfdefault'),'cmss')))`

This example must be in docs.
