### ISSUE TITLE
Import statements in example code snippets don't work

### ISSUE THREAD

**Issue by cbrummitt** [JelteF/PyLaTeX#153]
Has the documentation gotten out of sync with the code (perhaps when "things [were] moved an renamed" in the version `1.0` release)? When I try to run example code snippets, I  frequently get `ImportError`s. 

For example, for the [complex code example](https://jeltef.github.io/PyLaTeX/latest/examples/complex_report.html#the-code), the import statement gives the following error:

```
>>>from pylatex import Document, PageStyle, Head, Foot, MiniPage, \
    StandAloneGraphic, MultiColumn, Tabu, LongTabu, LargeText, MediumText, \
    LineBreak, NewPage, Tabularx, TextColor, simple_page_number 
ImportError: cannot import name 'PageStyle'
```
Among the objects in this import statement, I can only import four of them: `Document, MultiColumn, Tabu, LongTabu`.

I'm running pylatex `v1.0.0` of pylatex and python `v3.5.2`.

**Comment by JelteF** [comment]
Lots of new features were added in the 1.1.0 release. I'm quite sure you're missing those. Please reopen if updating does not fix the problem.
