### ISSUE TITLE
More specific exception when pdflatex and latexmk are missing

### ISSUE THREAD

**Issue by adamhayes** [JelteF/PyLaTeX#158]
Working on Windows, when neither pdflatex, nor latexmk can be called, the general WindowsError is raised:

    WindowsError: [Error 2] The system cannot find the file specified

because it is the result of a failed `subprocess.check_output()` shell call.  This is easily mistaken for a missing user file (.tex file, etc.), and it requires some digging into the pylatex code to determine that this is due to a missing latex utility.   The exception is raised in `def generate_pdf` of `class Document` in `document.py` here:

    304         else:
    305             # If none of the compilers worked, raise the last error
    306             raise(os_error)

Could a new exception type be added to make this problem easier to debug?  :

**Comment by JelteF** [comment]
That indeed sounds like a better way to go, could you make a pull request for that? There's already custom exceptions defined here: https://github.com/JelteF/PyLaTeX/blob/master/pylatex/errors.py Something like CompilerNotFound error would be a good name.

**Comment by dedeco** [comment]
I had this exception with python 3, Ubuntu 16.04.3 LTS when I'm using nginx (user:www-data). But when using an virtualenv (on server) the pdf is created and I'm 100% sure that the compiler are installed. 

So I don't think that this exception is only CompilerNotFound, can be more than only this. I didn't find any solution yet.

`Traceback (most recent call last):
  File /env/flask3/lib/python3.5/site-packages/flask/app.py, line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File /env/flask3/lib/python3.5/site-packages/flask/app.py, line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File /env/flask3/lib/python3.5/site-packages/flask/app.py, line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File /env/flask3/lib/python3.5/site-packages/flask/_compat.py, line 33, in reraise
    raise value
  File /env/flask3/lib/python3.5/site-packages/flask/app.py, line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File /env/flask3/lib/python3.5/site-packages/flask/app.py, line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File /env/flask3/lib/python3.5/site-packages/flask_login/utils.py, line 228, in decorated_view
    return func(*args, **kwargs)
  File ./web/frontend/views.py, line 690, in report
  File ./web/frontend/printr.py, line 205, in generate_files
  File /env/flask3/lib/python3.5/site-packages/pylatex/document.py, line 274, in generate_pdf
    raise(os_error)
  File /env/flask3/lib/python3.5/site-packages/pylatex/document.py, line 228, in generate_pdf
    stderr=subprocess.STDOUT)
  File /usr/lib/python3.5/subprocess.py, line 626, in check_output
    **kwargs).stdout
  File /usr/lib/python3.5/subprocess.py, line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File /usr/lib/python3.5/subprocess.py, line 947, in __init__
    restore_signals, start_new_session)
  File /usr/lib/python3.5/subprocess.py, line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: pdflatex`

In Stackoverflow I find this question whithout a correct answer: https://stackoverflow.com/questions/40039763/pylatex-error-when-generate-pdf-file-no-such-file-or-directory

**Comment by JelteF** [comment]
Is the pdflatex command in your PATH when running the python script? And be
really sure that you have installed texlive and if it then still doesn't
work, try install latexmk as well.

**Comment by dedeco** [comment]
Thanks. Sorry about my mistake. Latexmk and pdflatex was already installed. 

The problem was the PATH. I was running an web site using Flask, hosting using uWsgi as service, and PATH was set just whith my virtualenv. 

So I fixed adding ":/usr/bin" and worked, see bellow:

`[Unit]
Description=uWSGI instance to serve myproject
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/sites/simapp
Environment="PATH=/env/flask3/bin:/usr/bin"
ExecStart=/env/flask3/bin/uwsgi --ini /sites/simapp/simapp.ini

[Install]
WantedBy=multi-user.target
`
