### ISSUE TITLE
Generate tex documents without preamble so they can be used as child documents

### ISSUE THREAD

**Issue by Delosari** [JelteF/PyLaTeX#169]
I want to thank the developer to this great contribution and I wonder if I could ask for help or maybe request one feature:

I use pylatex (among other things) to generate nice tables from text files. I would like to include these tables in latex manuscripts as child documents.

However, to do that you need to delete the preamble for the code to work.

Which would be the best approach to generate a latex document without any preamble using pylatex?

Thanks again

**Comment by JelteF** [comment]
Just use the generate_tex method on the table class.
https://jeltef.github.io/PyLaTeX/current/usage.html#the-classes

You can then use \input{} to include it in your own tex file.

**Comment by JelteF** [comment]
I'll close this issue as this is possible, please reopen if you have issues with it.
