### ISSUE TITLE
Add a way to disable loading inputenc and fontenc

### ISSUE THREAD

**Issue by estan** [JelteF/PyLaTeX#170]
When using `xelatex` as the compiler, you don't want `inputenc` and `fontenc` loaded at all, since UTF-8 is assumed for the input, and the `fontspec` (pulled in by `xltxtra`) should be used instead.

But currently I can't see a way of disabling loading of these packages. The `Document` class adds them unconditionally to `.packages`.

**Comment by JelteF** [comment]
You're right. A pull request is appreciated, should be as simple as checking for None in these places:
https://github.com/JelteF/PyLaTeX/blob/master/pylatex/document.py#L86-L87
