### ISSUE TITLE
New version release request!

### ISSUE THREAD

**Issue by dgrigonis** [JelteF/PyLaTeX#175]
See [https://github.com/JelteF/PyLaTeX/pull/152](https://github.com/JelteF/PyLaTeX/pull/152)

I would be happy to issue PR removing "%" before you release new version. I am ok with leaving them as well. Either way would be nice to see new version released.

**Comment by JelteF** [comment]
Released a new one regarding the percent change could you make another issue with an example where it results in incorrect code?
