### ISSUE TITLE
make_temp_dir() in windows

### ISSUE THREAD

**Issue by dgrigonis-gmt** [JelteF/PyLaTeX#177]
Hello again,

I am using the package on both windows and unix. On unix all is fine, but on windows there is an issue with `tempfile`:

```python
_tmp_path = os.path.abspath(
    os.path.join(
        tempfile.gettempdir(),
        u"pylatex"
    )
)

Out[5]: u'c:\\users\\userna~1\\appdata\\local\\temp\\pylatex'
```

2 problems are present:

1. `\\` is not a valid separator in latex. A hack is simply `replace(r'\\', '/')`
2. `userna~1` has been truncated from `username`.

My hacky way of fixing this is:

```python
from pylatex.figure import Figure as Figure_

class Figure(Figure_):
    def _save_plot(self, *args, **kwargs):
        tmp_path = make_temp_dir()
        tmp_path = tmp_path.replace('\\', '/')
        tmp_path = re.sub(r'/([^/]*?~.)/', '/' + getpass.getuser() + '/', tmp_path)
        extension = kwargs.pop('extension', 'pdf').strip('.')
        filename = '{}.{}'.format(str(uuid.uuid4()), extension)
        filepath = posixpath.join(tmp_path, filename)
        plt.savefig(filepath, *args, **kwargs)
        return filepath
```

However, would be good to come up with global solutions for these (i.e. path should be converted to posix everywhere, thus some utility function for that might do). I will give it a try when I am in the mood. Posting this in case you can come up with some quick fixes.

**Comment by JelteF** [comment]
1. Can be fixed by using the `fix_filename` function from the `utils` submodule. This should already be used by  `Figure`. What code are you using that this doesn't work. 
2. Sounds like this is not really an issue, because this is simply the temporary directory that Windows provides. Maybe you're running into the same issue as #147 which might be fixed by #149.

**Comment by JelteF** [comment]
I just merged #149 with some changes. Could you let me know if it fixes your issue?

**Comment by dgrigonis-gmt** [comment]
1. I see that it has been fixed.
2. I see detokenize wrapps `-` and `~`, but isn't there a problem of truncating username? I can not use this in my command line either... This is what I get anyways:
```latex
! Package pdftex.def Error: File `c:/users/userna\textasciitilde {}1/appdata/lo
cal/temp/pylatex/5b7a12f4{-}764e{-}46a1{-}82ea{-}581e92980d55.jpg' not found.
```

Original filename: `u'c:\\users\\userna~1\\appdata\\local\\temp\\pylatex/a6e354d1-6c3d-49e1-a0ae-bfc192fa1bf5.jpg'`

**Comment by JelteF** [comment]
hmm, that seems like a `NoEscape` is needed at the end of `fix_filename`. Could you try that out to see if it works? The truncating itself should not be the problem, since that is just the way windows temporary directories work.

**Comment by dgrigonis-gmt** [comment]
Still not. See path value before and after detokenize

```python
    # fixed_path = u'c:/users/dgrigo~1/appdata/local/temp/pylatex/da805a56-f7aa-44a3-8c98-d59f64ae3ae6.jpg'

    if '~' in fixed_path:
        fixed_path = detokenize(fixed_path)

    # fixed_path = \detokenize{c:/users/dgrigo\textasciitilde{}1/appdata/local/temp/pylatex/da805a56{-}f7aa{-}44a3{-}8c98{-}d59f64ae3ae6.jpg}
```

**Comment by dgrigonis-gmt** [comment]
Srry for replying without properly looking at it. So need to set `escape=False` in fix_filename:

```python
    if '~' in fixed_path:
        fixed_path = detokenize(fixed_path, escape=False)
```

**Comment by JelteF** [comment]
Wait, which version are you using? Current master doesn't have the `detokenize` function: https://github.com/JelteF/PyLaTeX/blob/master/pylatex/utils.py#L144

Could you check again with the code from the current master?

**Comment by dgrigonis-gmt** [comment]
`escape=False` for `detokenize` solves the issue!

I am using newest release. Just copying the code that you suggested:

```python
from pylatex.figure import Figure as Figure_, StandAloneGraphic

class Figure(Figure_):
    def add_image(self, filename, **_3to2kwargs):
        if 'placement' in _3to2kwargs: placement = _3to2kwargs['placement']; del _3to2kwargs['placement']
        else: placement = NoEscape(ur'\centering')
        if 'width' in _3to2kwargs: width = _3to2kwargs['width']; del _3to2kwargs['width']
        else: width = NoEscape(ur'0.8\textwidth')
        if width is not None:
            if self.escape:
                width = escape_latex(width)
            width = u'width=' + unicode(width)
        if placement is not None:
            self.append(placement)
        self.append(StandAloneGraphic(image_options=width,
                                      filename=fix_filename(filename)))

def fix_filename(path):
    path_parts = path.split('/' if os.name == 'posix' else '\\')
    dir_parts = path_parts[:-1]
    filename = path_parts[-1]
    file_parts = filename.split('.')
    if len(file_parts) > 2:
        filename = '{' + '.'.join(file_parts[0:-1]) + '}.' + file_parts[-1]
    dir_parts.append(filename)
    fixed_path = '/'.join(dir_parts)
    if '~' in fixed_path:
        fixed_path = NoEscape(r'\detokenize{' + fixed_path + '}')
    return fixed_path
```

**Comment by dgrigonis-gmt** [comment]
In [https://github.com/JelteF/PyLaTeX/pull/149](https://github.com/JelteF/PyLaTeX/pull/149) you said you merged it. What happened there? The PR looks good and with a fix I noted above it should solve win path issues.

**Comment by JelteF** [comment]
I decided detokenize was not needed outside fix_filename. So I just
integrated it there. I forgot about the escaping though. Good that it works
when you add it.

I'll try to add it to the library in a little while. However, I have to
check what happens when you embed other dangerous characters in the path
string too be sure it won't break or cause security issues because of not
escaping them.

**Comment by dgrigonis** [comment]
Have a look at [https://github.com/JelteF/PyLaTeX/pull/178/files](https://github.com/JelteF/PyLaTeX/pull/178/files). I have separated detokenize out. I think it might prove useful on its own in the future.

**Comment by dgrigonis-gmt** [comment]
So yeah, all works in master

**Comment by JelteF** [comment]
Does it work without the `NoEscape`?

**Comment by dgrigonis** [comment]
Yes, it does. I wasn't checking the right code. Thanks

**Comment by dgrigonis** [comment]
I thought you have just replicated what was in the PR that you referenced. Wasn't visible what you did and I can not install master easily as I am using conda. `conda skeleton` does not have `git` option...

**Comment by dgrigonis** [comment]
Maybe you could put it on [conda-forge](https://conda-forge.github.io/#add_recipe)? Or work out some other way for conda users?

**Comment by JelteF** [comment]
I'm don't know much about conda, but can't you still also use pip when using conda? Otherwise maybe you can use something like this: http://stackoverflow.com/a/32799944/2570866

I'll try to release again somewhere this week.

**Comment by dgrigonis** [comment]
This is one possible way - there are few others, but all of them are a bit messy. For testing I can easily do `pip install`, which is always an option. However, recipe to build master would be a nice thing. Release would be apprieciated.

**Comment by JelteF** [comment]
Just released a new version

**Comment by dgrigonis** [comment]
Much appreciated. Seems that all works fine now and I will remove the last pylatex hack from my local lib.
