### ISSUE TITLE
Import error: cannot import name 'Document'

### ISSUE THREAD

**Issue by pnmartinez** [JelteF/PyLaTeX#199]
Hi, newbie here.

I'm having a problem **running the Basic Example** (https://jeltef.github.io/PyLaTeX/latest/examples/basic.html).

I copied the code to a .py and tried to run it, but I get the following error:

```
Traceback (most recent call last):
  File "basic_example.py", line 1, in <module>
    from pylatex import Document, Section, Subsection, Command
  File "C:\Users\Usuario\Desktop\s\pylatex.py", line 3, in <module>
    from pylatex import Document, Section, Subsection, Tabular, Math, TikZ, Axis
, \
ImportError: cannot import name 'Document'
```
My pip version is 9+, and python 3.6+. 

All and all, keep up the amazing work Mr. Fennema!

**Comment by JelteF** [comment]
You have a file called pylatex.py yourself as well, according to the error
message. That breaks import resolution in Python. If you name it anything
else it should work.

**Comment by pnmartinez** [comment]
Yup, I made a fool out of myself there. After getting some missing components, it works.

For those in my situation, the fix is easy if you read through the logs.

- I had to install **Pearl**.

- Afterwards I had to install **two LaTeX packages manually**, from the MikTex package manager: latexmk and lastpage.

Thanks Fennema!!
