### ISSUE TITLE
Multicolum with align='p{6cm}'

### ISSUE THREAD

**Issue by lcpt** [JelteF/PyLaTeX#200]
Hi.

First of all; thanks for your work!

I think I've found an issue: if I wrote:
pylatex.table.MultiColumn(3,align= 'p[6cm}',data= 'some text')

I get the following output (note the backslashes before the braces at both sides of paragraph width):
\multicolumn{3}{p\{6cm\}}{some text}

How can I get the alignment parameter without the backslashes?

Thanks!

**Comment by JelteF** [comment]
I feel like the backslashes are not copied correctly. But could you try to wrap the alignment with NoEscape(str)? That should probably work.

**Comment by lcpt** [comment]
Yeah NoEscape('p{6cm}') works like a charm. Thank you very much!
(and yeah the backslashes were gone from my post).

**Comment by JelteF** [comment]
Good to hear, keep in mind that you should never use unescaped user input in `NoEscape`. Otherwise you open yourself up to command execution. You can escape user input manually by using the `escape` function.
