### ISSUE TITLE
Header is not compiling, following example in the documentation

### ISSUE THREAD

**Issue by f1uk3r** [JelteF/PyLaTeX#208]
I am trying to use this module to create a header in latex and following examples given in the documentation. But even though .tex file gives the same result but on compiling header is nowhere to be seen.

geometry_options = {"margin":"1in", "includeheadfoot": True}
doc = Document(geometry_options=geometry_options)

header = PageStyle("header")
with header.create(Head("C")) as header_center:
    with header_center.create(MiniPage(width=NoEscape(r"0.49\textwidth"), pos='c', align='r')) as wrapper:
        wrapper.append(LargeText(bold("EdHusk")))
        wrapper.append(MediumText(bold("Personalized Learning at your Doorstep")))

doc.preamble.append(header)

**Comment by hygull** [comment]
I am not sure but your above code will work fine if you pass 1 more keyword argument named `data` as the below code presents. I have tried it in my system with `pylatex 1.3.0` and it creates PDF.

	from pylatex import Document, PageStyle, Head, MiniPage, Foot, LargeText, \
	    MediumText, LineBreak, simple_page_number, HugeText
	from pylatex.utils import bold, NoEscape

	geometry_options = {"margin":"1in", "includeheadfoot": True}
	doc = Document(geometry_options=geometry_options, data="f1uk3r's issue")

	header = PageStyle("header")

	with header.create(Head("C")) as header_center:
		with header_center.create(MiniPage(width=NoEscape(r"0.49\textwidth"), pos='c', \
		align='r')) as wrapper:
			wrapper.append(LargeText(bold("EdHusk")))
			wrapper.append(MediumText(bold("Personalized Learning at your Doorstep")))

	doc.preamble.append(header)
	doc.change_document_style("header")

	doc.generate_pdf("header_center", clean_tex=True)


Now you have to look for good alternative as using `data` keyword argument in Document() constructor adds text to the generated PDF document.

**Comment by f1uk3r** [comment]
Thanks for the reply.
That data argument wasn't much helpful.
Though doc.change_document_style('header') worked
