### ISSUE TITLE
No example to add indented text after doc creation, except lorem epsum example

### ISSUE THREAD

**Issue by hygull** [JelteF/PyLaTeX#209]
There is no  more examples that explains how to indent our text blocks.

One of the way is

` doc = Document(data=NoEscape(lorem))`

that you can find at https://jeltef.github.io/PyLaTeX/latest/examples/config.html.

But what if I want to add the indented text after doc creation using

`doc = Document()` statement

So that beautiful letterhead pdf documents could be created. 

The PyLaTex doc is excellent but I am not finding any example related to the above issue.

I am not sure whether there is any way to do this(already present in the documentation). 

I tried a lot but failed.  Suggest me any example please.

What I want is I want to create letterhead documents something like in this [https://www.latextemplates.com/cat/formal-letters](https://www.latextemplates.com/cat/formal-letters).

I am able to add logo, right header text etc. but I am unable to indent text blocks.

**Comment by JelteF** [comment]
I just released a version 1.3.0, which includes some extra classes. I think the Paragraph class should work for you: https://jeltef.github.io/PyLaTeX/latest/pylatex/pylatex.section.html#pylatex.section.Paragraph

Please reopen the issue if that's not the case.

**Comment by hygull** [comment]
I tried it with PyLaTeX 1.3.0, I saw the below o/p terminal

	$ pip freeze | grep -i "pylatex"
	PyLaTeX==1.3.0

	$ python paragraph.py
	Traceback (most recent call last):
	  File "paragraph.py", line 1, in <module>
	    from pylatex import Document, Paragraph;
	ImportError: cannot import name Paragraph

I am not sure, Look at my code below.

	from pylatex import Document, Paragraph;

	doc = Document("paragraph");
	text1 = """At vero eos et accusamus et iusto odio dignissimos ducimus 
	qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores 
	et quas molestias excepturi sint occaecati cupiditate non provident, similique 
	sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.
	Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, 
	cum soluta nobis est eligendi optio cumque nihil impedit quo minus id.""";

	text2 = """quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor 
	repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessit
	atibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. 
	Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus 
	maiores alias consequatur aut perferendis doloribus asperiores repellat.""";

	text3 = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
	incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
	exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute 
	irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
	pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia 
	deserunt mollit anim id est laborum""";

	with doc.create(Paragraph("Title1")):
		doc.append(text1);
		doc.append(text2);
		doc.append(text3);

	doc.generate_pdf(clean_tex=True);

Suggest me where I am wrong.

**Comment by JelteF** [comment]
And regarding the import error. You should do `from pylatex.section import Paragraph`. Apparently it's not exported in the main module.

**Comment by JelteF** [comment]
Finally you could also try doing this:

```
doc = Document()
doc.content_separator = '\n\n' # Separator for paragraphs in LaTeX
doc.append(paragraph1)
doc.append(paragraph2)
```

Or you could take a look at the `separate_paragraph` attribute of latex classes.

**Comment by JelteF** [comment]
An example with `Paragraph` would be:
```
with doc.create(Paragraph("")):
	doc.append(text1);
with doc.create(Paragraph("")):
	doc.append(text2);
with doc.create(Paragraph("")):
	doc.append(text3);
```

**Comment by hygull** [comment]
Thanks **JelteF**. Now import error got resolved.

Let me try to accomplish my original goal with paragraphs i.e creation of letterhead pdf document.

Thanks again.

**Comment by hygull** [comment]
Any suggestion about creating A4, A5, A6 size pdfs using `PyLaTeX`.

**Comment by JelteF** [comment]
You should be able to change the `document_class`/`document_options` parameter of `Document` to achieve this. By setting it to a `Command` that would be this: https://tex.stackexchange.com/questions/22917/a5paper-setting-not-taking-effect

One big tip is always to use `generate_tex` and see the resulting `.tex` file when debugging btw.

**Comment by hygull** [comment]
Thanks @JelteF .  

I am trying to use `font_size = "10pt"` with `Document()` constructor but it is failing.

**ISSUSES**:-

* if I am using `doc.create(Paragraph(""))` then it is adding space at the beginning of each paragraph. 

* `doc.content_separator = "\n\n\n\n"` , `doc.content_separator = "\n\n"`, `doc.content_separator = "\t\t"` all are producing the same pdf.

Is there any option to overcome it?
