### ISSUE TITLE
compile to outside directory

### ISSUE THREAD

**Issue by asi14** [JelteF/PyLaTeX#211]
I want to keep my python source files and latex output files in separate folders by compiling them in an outside folder. There doesn't seem to be any information about it in the documentation, so is there a way to specify in my code to pylatex to compile to another folder besides the python file's original directory?

**Comment by JelteF** [comment]
you can use change the default_filepath or the filepath arguments of generate_pdf:
https://jeltef.github.io/PyLaTeX/current/pylatex/pylatex.document.html#pylatex.document.Document
