### ISSUE TITLE
Template - Jinja2 integration

### ISSUE THREAD

**Issue by Montagnard** [JelteF/PyLaTeX#218]
Hi, is there a possible way to work with PyLaTex with templates in a way similar than JInja2 ?

If not, is there a way to work with PyLaTex and Jinja2 ? Are there function that gives string from mathematical objects coming from numpy for example ?

Thanks :)

**Comment by Montagnard** [comment]
Ok, I found in the source code the method dumps_content for a Matrix. I think it can be useful to have something on it in the Documentation

**Comment by JelteF** [comment]
Probably the dumps method makes more sense in most cases.
