### ISSUE TITLE
compile tex file containing Chinese

### ISSUE THREAD

**Issue by Freakwill** [JelteF/PyLaTeX#227]
I compiled tex files containing Chinese, and got error about encoding.
I have subclass-ed Document to inject `%!TEX program = xelatex`, in order to handle with Chinese. It can be compiled **manually** （cmd-B in sublime）, but `self.generate_pdf(clean_tex=False)` gave error. How do I fix it?

**Comment by scz526600266** [comment]
Did u solve that problem?

**Comment by yangdaweihit** [comment]
```
doc = Document()
doc.packages.append(Package('ctex', options=r'UTF8'))
...
doc.generate_pdf(compiler='xelatex')

```
