### ISSUE TITLE
 Pylatex is not threadsafe

### ISSUE THREAD

**Issue by AlexBardDev** [JelteF/PyLaTeX#254]
Hi,

Pylatex is not threadsafe and it plays with current_working_directory. So, if you have 1 first error, then you could have several other errors like : 

 File "/home/user/env/lib/python3.6/site-packages/pylatex/document.py", line 203, in generate_pdf
    cur_dir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

This error is not related to the first one(=the real one), but it spams your traceback.

**Comment by jeffheaton** [comment]
Yes, I've noticed this too.

**Comment by stiefel40k** [comment]
Is this going to be fixed eventually? I'm trying to build a webapp where pylatex is used in a temporary directory, however this bug completely ruins how the webapp works. If you want I can provide a basic example program with which this problem can be shown.

**Comment by JelteF** [comment]
A PR for this is welcome, but I don't have time myself to work on this.

**Comment by JelteF** [comment]
This is fixed now in PyLaTeX 1.3.2, for python versions 3.6+.
