### ISSUE TITLE
Chapter, Subparagraph, Paragraph Classes Cannot be called

### ISSUE THREAD

**Issue by bstone22** [JelteF/PyLaTeX#256]
NameError when trying to use Chapter, Subparagraph, and Paragraph classes. Section, Subsection and Subsubsections work fine.

**Comment by JelteF** [comment]
Try importing from pylatex.section

**Comment by bstone22** [comment]
Thanks for the reply! Importing from the section class got it to work. Thanks again for the replay and a wonderful package!
