### ISSUE TITLE
Parameters of generate_pdf

### ISSUE THREAD

**Issue by teodorwisniewski** [JelteF/PyLaTeX#267]
Hi Jelte,
you are doing amazing work here! thank you. I've been coming back to this repository many times.
I have a hard time finding the reason why my code does not create table of contents (ToC). If I open my "tex" file generated by my code and I compile it with TexMaker, the table of contents is created, but when I do it with "generate_pdf", it does not work. 90% it creates a pdf file without ToC, 10 % it creates a pdf with ToC. It seems to be completly random.

Here is the way my function:
doc.generate_pdf(output_name,clean=True, clean_tex=False,compiler='pdflatex',compiler_args =[])

Another issue concerns the exeption, it gives me during "generate_pdf" excecution:
"'utf-8' codec can't decode byte 0xe9 in position 26306: invalid continuation byte"

What can I do to make it work smoothly?

Thank you in advance!
Teodor

**Comment by JelteF** [comment]
Have you tried installing latexmk and using that as the compiler argument
(or not supplying it at all)? It will rerun pdflatex multiple times, which
I think is necessary for a TOC.

**Comment by teodorwisniewski** [comment]
Hi Jelte, thank you for your quick response. 
I've installed latexml and changed my code to:
doc.generate_pdf(output_name,clean=True, clean_tex=False,compiler='latexmk') 

It generated a pdf file without TOC. When I complile the resulting tex file with TexMaker, I get a pdf file with TOC. 

I guess I should change somehow compiler_args =[], what should I put in that list to make it work?

Teodor
