### ISSUE TITLE
generate_pdf with bookmarks

### ISSUE THREAD

**Issue by antipisa** [JelteF/PyLaTeX#268]
Hi Jeff,
how do you enable bookmarks to appear on a pdf sidebar so that the sections are enumerated? For instance in this example: 
https://jeltef.github.io/PyLaTeX/current/examples/basic.html
Calling 
```
doc.packages.append(Package('bookmarks'))
doc.generate_pdf('basic_maketitle', clean_tex=False)
```
does not seem to have an effect.

**Comment by JelteF** [comment]
Try installing latexmk, it will be used automatically as a compiler and probably fixes this.

**Comment by TianZhengjie-lxc** [comment]
pip install latexmk.py
