### ISSUE TITLE
CompilerError: No LaTex compiler was found

### ISSUE THREAD

**Issue by vfrossa** [JelteF/PyLaTeX#274]
Hi!
I am using PyLaTeX on a Juypiter Notebook (on Databricks Community).
When generating the PDF with `doc.generate_pdf(clean_tex=False)` I get the error:

![grafik](https://user-images.githubusercontent.com/29702965/79670634-d415e800-81c4-11ea-9407-e0b958ebfda3.png)

I have installed, both pdflatex and latexmk.py using pip.
Using the option `compiler=pdflatex`, I also receive the error shown above. 
Using the option `compiler=latexmk.py`, I receive the following error:
![grafik](https://user-images.githubusercontent.com/29702965/79670713-4b4b7c00-81c5-11ea-80cd-4bd08f1aaa02.png)

I have added the locations of both pdflatex and latexmk.py to the PATH using
`import sys`
`sys.path.append('respective_path')`, whereas respective_path is the path to the file.

Do you have any suggestion how to make this work?

EDIT: I've tested it on my local machine (Spyder, no jupyter), and there it works.

**Comment by akhilvasvani** [comment]
I too had a similar problem. I was trying to run PyLatex on Google Colabs and it was not compiling.
What I did:

I installed the following packages in this order.
```
sudo pip3 install pylatex
sudo pip3 install pdflatex==0.1.3
sudo apt-get install latexmk
sudo apt-get install -y texlive-latex-extra
```

Then when I ran, 
``` 
from pylatex import Document, Section, Subsection, Command
from pylatex.utils import italic, NoEscape
import pdflatex
  
doc = Document('test_limit')
fill_document(doc)
doc.generate_tex()
doc.generate_pdf('test_limit')
```

Note: ```fill_document()``` is not a built-in function with the PyLaTex library.

References:

[How To Install "texlive-latex-extra" Package on Ubuntu](https://zoomadmin.com/HowToInstall/UbuntuPackage/texlive-latex-extra)

**Comment by joshfinley** [comment]
These apt dependencies really should be listed in the readme somewhere. There's a lot of tickets related to this

**Comment by JelteF** [comment]
Feel free to make a PR to add OS specific dependencies somewhere.

**Comment by catauggie** [comment]
> I too had a similar problem. I was trying to run PyLatex on Google Colabs and it was not compiling. What I did:
> 
> I installed the following packages in this order.
> 
> ```
> sudo pip3 install pylatex
> sudo pip3 install pdflatex==0.1.3
> sudo apt-get install latexmk
> sudo apt-get install -y texlive-latex-extra
> ```
> 
> Then when I ran,
> 
> ```
> from pylatex import Document, Section, Subsection, Command
> from pylatex.utils import italic, NoEscape
> import pdflatex
>   
> doc = Document('test_limit')
> fill_document(doc)
> doc.generate_tex()
> doc.generate_pdf('test_limit')
> ```
> 
> Note: `fill_document()` is not a built-in function with the PyLaTex library.
> 
> References:
> 
> [How To Install "texlive-latex-extra" Package on Ubuntu](https://zoomadmin.com/HowToInstall/UbuntuPackage/texlive-latex-extra)

maybe do you know what should I do on Windows 10?

**Comment by catauggie** [comment]
> Hi! I am using PyLaTeX on a Juypiter Notebook (on Databricks Community). When generating the PDF with `doc.generate_pdf(clean_tex=False)` I get the error:
> 
> ![grafik](https://user-images.githubusercontent.com/29702965/79670634-d415e800-81c4-11ea-9407-e0b958ebfda3.png)
> 
> I have installed, both pdflatex and latexmk.py using pip. Using the option `compiler=pdflatex`, I also receive the error shown above. Using the option `compiler=latexmk.py`, I receive the following error: ![grafik](https://user-images.githubusercontent.com/29702965/79670713-4b4b7c00-81c5-11ea-80cd-4bd08f1aaa02.png)
> 
> I have added the locations of both pdflatex and latexmk.py to the PATH using `import sys` `sys.path.append('respective_path')`, whereas respective_path is the path to the file.
> 
> Do you have any suggestion how to make this work?
> 
> EDIT: I've tested it on my local machine (Spyder, no jupyter), and there it works.

hi. did you solve the problem?

**Comment by vfrossa** [comment]
This solved the issue back then.
