### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by Vayel** [JelteF/PyLaTeX#28]
Hi!

I wonder whether it would be interesting to implement unit tests like that:

```python
doc = Document()

# ...

tex = """
...
"""

assert doc.dumps() == tex
```

Thanks!

**Comment by JelteF** [comment]
I have already thought about this for a bit, but I think it would mostly annoy the hell out of me every time stuff changes a bit (like an extra space or an extra return) or when a new package is used by default. I think the current "tests" are the sweetspot I like. Just run all the examples and tests and if it compiles it still compiles it is probably all right.
