### ISSUE TITLE
why can't run pylatex in linux normally? even examples in https://jeltef.github.io/PyLaTeX/latest/examples/

### ISSUE THREAD

**Issue by lotus-devo** [JelteF/PyLaTeX#281]
the program that I copy in the https://jeltef.github.io/PyLaTeX/latest/examples/ like this:
import pylatex as pl
from pylatex.utils import NoEscape
from pylatex import Command
from pylatex import Package
from pylatex import Figure
import os

videoNumber = 1
slideNumber = 5

class Form(pl.base_classes.Environment):
    """A class to wrap hyperref's form environment."""

    _latex_name = 'Form'

    packages = [pl.Package('hyperref')]
    escape = False
    content_separator = "\n"

geometry_options = {
    "head": "1pt",
    "margin": "0.2in",
    "bottom": "0.2in",
    "includeheadfoot": False}
doc = pl.Document(geometry_options=geometry_options)

with doc.create(Figure(position='h!')) as slide_pic:
                slide_pic.add_image("1.jpg",width=NoEscape("\linewidth"))

dirname = os.getcwd()
filename = os.path.join(dirname, 'Text And Slides\\' + str(videoNumber) + '\\Text\\' + str(slideNumber))
with open(filename+".txt", 'r',encoding="utf8") as myfile:
    text=myfile.read().replace('\n', '')
doc.append(text)
doc.append(NoEscape(r"\newcommand\measurepage{\the\dimexpr\pagegoal-\pagetotal-\baselineskip\relax}"))
with doc.create(Form()):
    doc.append(Command('noindent'))
    doc.append(Command('TextField',
               options=["name=multilinetextbox", "multiline=true",
                        NoEscape("width=\linewidth"),NoEscape("height=\measurepage")],
               arguments=''))

doc.generate_tex(str(slideNumber))
doc.generate_pdf(str(slideNumber))

it will show the error ：
Traceback (most recent call last):
  File "test1.py", line 2, in <module>
    import pylatex as pl
  File "/home/dongl/.local/lib/python3.5/site-packages/pylatex/__init__.py", line 8, in <module>
    from .basic import HugeText, NewPage, LineBreak, NewLine, HFill, LargeText, \
  File "/home/dongl/.local/lib/python3.5/site-packages/pylatex/basic.py", line 9, in <module>
    from .base_classes import CommandBase, Environment, ContainerCommand
  File "/home/dongl/.local/lib/python3.5/site-packages/pylatex/base_classes/__init__.py", line 8, in <module>
    from .latex_object import LatexObject
  File "/home/dongl/.local/lib/python3.5/site-packages/pylatex/base_classes/latex_object.py", line 9, in <module>
    from ordered_set import OrderedSet
  File "/home/dongl/.local/lib/python3.5/site-packages/ordered_set.py", line 51, in <module>
    class OrderedSet(MutableSet[T], Sequence[T]):
  File "/home/dongl/.local/lib/python3.5/site-packages/ordered_set.py", line 186, in OrderedSet
    def update(self, sequence: SetLike[T]) -> int:
  File "/usr/lib/python3.5/typing.py", line 546, in __getitem__
    "Cannot subscript an existing Union. Use Union[u, t] instead.")
TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.

how can I solve this problem?

**Comment by JelteF** [comment]
Siunds like a bug in a new version of ordered_set, which is a dependency of PyLaTeX. Please report this there: https://github.com/LuminosoInsight/ordered-set

**Comment by JelteF** [comment]
I changed the dependencies to use an old version of ordered-set for python 3.5
