### ISSUE TITLE
how can i use pylatex to edit Chinese?

### ISSUE THREAD

**Issue by lotus-devo** [JelteF/PyLaTeX#283]
I tried to use pylatex to edit Chinese, but there are something  wrong like following:

Traceback (most recent call last):

  File "C:\Users\lotus\.spyder-py3\未命名0.py", line 94, in <module>
    gene_pdf()

  File "C:\Users\lotus\.spyder-py3\未命名0.py", line 92, in gene_pdf
    doc.generate_pdf('full',compiler='xelatex', clean_tex=False)

  File "E:\anoconda\lib\site-packages\pylatex\document.py", line 245, in generate_pdf
    **check_output_kwargs)

  File "E:\anoconda\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "E:\anoconda\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

CalledProcessError: Command '['xelatex', '--interaction=nonstopmode', 'C:\\Users\\lotus\\.spyder-py3\\full.tex']' returned non-zero exit status 1.

How can I solve this error?

**Comment by lotus-devo** [comment]
The following is my program:
import xlrd
from pylatex.utils import bold
from pylatex.document import Document
from pylatex.headfoot import PageStyle, Head, Foot
from pylatex.position import MiniPage
from pylatex.section import Subsection
from pylatex.table import  MultiRow, Tabular
from pylatex.basic import LargeText
from pylatex.package import Package


def get_row_value(sample_ID):
    book = xlrd.open_workbook("D:/pylatex开发计划\样本信息_NeoTargeting.xlsx")
    table = book.sheet_by_name("Sheet1")
    row_Num = table.nrows
    col_Num = table.ncols
    
    key = table.row_values(17)
    for i in range(row_Num-1):
        d = {}
        if sample_ID in table.row_values(i):
            values =table.row_values(i)
            for x in range(col_Num):
                d[key[x]]=values[x]
            return d

s=get_row_value('JY99000110')

def gene_pdf():
    geometry_options = {"head": "40pt",
                        "margin": "0.7in",
                        "bottom": "0.6in",
                        "includeheadfoot": True
    }
    doc = Document(geometry_options=geometry_options)
    doc.packages.add(Package(''))
    header = PageStyle("firstpage")
    
    with header.create(Head("L")):
        header.append("甲状腺癌14基因检测报告")
    
    with header.create(Head("R")):
        header.append("NeoCura")
        
    with header.create(Foot("L")):
        header.append("深圳新合医学检验实验室")
        
    with header.create(Foot("C")):
        header.append("联系电话：0755-­86706127")
        
    with header.create(Foot("R")):
        header.append("官网：https://neocura.net")
        
    doc.preamble.append(header)
    doc.change_document_style("firstpage")
   
    
    with doc.create(MiniPage(align='l')):
        doc.append(LargeText(bold("1 Basic information and main quality control")))
        
    with doc.create(Subsection('Subject and sample information ')):
        with doc.create(Tabular('cccc',row_height=2, col_space="0.5cm")) as table:
            table.add_hline()   
            table.add_row(('姓名', s['姓名'], '样本类型', s['样本类型']),color='red')
            table.add_hline(1,4)
            table.add_row(('性别', s['性别'], '来源部位', s['来源部位']),color='green')
            table.add_hline(1,4)
            table.add_row('年龄',s['年龄'],'临床诊断',s['临床诊断'])
            table.add_hline(1,4)
            table.add_row('民族','', '肿瘤类型', s['肿瘤类型'])
            table.add_hline(1,4)
            table.add_row('籍贯','','肿瘤分期','')
            table.add_hline(1,4)
            table.add_row('受检者类型', '肿瘤患者','患者编号',s['患者编号'])
            table.add_hline(1,4)
            table.add_row('联系方式','','样本编号',s['样本编号'])
            table.add_hline(1,4)
            table.add_row('病理号','','报告编号',s['#报告编号'])
            table.add_hline(1,4)
            table.add_row('接收日期',s['接收日期'],'癌症细胞含量',s['肿瘤细胞含量'])
            table.add_hline(1,4)
            table.add_row('病理诊断',s['病理诊断'],'','')
            table.add_hline(1,4)
    doc.generate_pdf('full',compiler='xelatex', clean_tex=False)

gene_pdf()

**Comment by JelteF** [comment]
If you use `generate_tex()` instead of `generate_pdf()` you can see the full error you get.

**Comment by Freakwill** [comment]
> The following is my program:
> import xlrd
> from pylatex.utils import bold
> from pylatex.document import Document
> from pylatex.headfoot import PageStyle, Head, Foot
> from pylatex.position import MiniPage
> from pylatex.section import Subsection
> from pylatex.table import MultiRow, Tabular
> from pylatex.basic import LargeText
> from pylatex.package import Package
> 
> def get_row_value(sample_ID):
> book = xlrd.open_workbook("D:/pylatex开发计划\样本信息_NeoTargeting.xlsx")
> table = book.sheet_by_name("Sheet1")
> row_Num = table.nrows
> col_Num = table.ncols
> 
> ```
> key = table.row_values(17)
> for i in range(row_Num-1):
>     d = {}
>     if sample_ID in table.row_values(i):
>         values =table.row_values(i)
>         for x in range(col_Num):
>             d[key[x]]=values[x]
>         return d
> ```
> 
> s=get_row_value('JY99000110')
> 
> def gene_pdf():
> geometry_options = {"head": "40pt",
> "margin": "0.7in",
> "bottom": "0.6in",
> "includeheadfoot": True
> }
> doc = Document(geometry_options=geometry_options)
> doc.packages.add(Package(''))
> header = PageStyle("firstpage")
> 
> ```
> with header.create(Head("L")):
>     header.append("甲状腺癌14基因检测报告")
> 
> with header.create(Head("R")):
>     header.append("NeoCura")
>     
> with header.create(Foot("L")):
>     header.append("深圳新合医学检验实验室")
>     
> with header.create(Foot("C")):
>     header.append("联系电话：0755-­86706127")
>     
> with header.create(Foot("R")):
>     header.append("官网：https://neocura.net")
>     
> doc.preamble.append(header)
> doc.change_document_style("firstpage")
> 
> 
> with doc.create(MiniPage(align='l')):
>     doc.append(LargeText(bold("1 Basic information and main quality control")))
>     
> with doc.create(Subsection('Subject and sample information ')):
>     with doc.create(Tabular('cccc',row_height=2, col_space="0.5cm")) as table:
>         table.add_hline()   
>         table.add_row(('姓名', s['姓名'], '样本类型', s['样本类型']),color='red')
>         table.add_hline(1,4)
>         table.add_row(('性别', s['性别'], '来源部位', s['来源部位']),color='green')
>         table.add_hline(1,4)
>         table.add_row('年龄',s['年龄'],'临床诊断',s['临床诊断'])
>         table.add_hline(1,4)
>         table.add_row('民族','', '肿瘤类型', s['肿瘤类型'])
>         table.add_hline(1,4)
>         table.add_row('籍贯','','肿瘤分期','')
>         table.add_hline(1,4)
>         table.add_row('受检者类型', '肿瘤患者','患者编号',s['患者编号'])
>         table.add_hline(1,4)
>         table.add_row('联系方式','','样本编号',s['样本编号'])
>         table.add_hline(1,4)
>         table.add_row('病理号','','报告编号',s['#报告编号'])
>         table.add_hline(1,4)
>         table.add_row('接收日期',s['接收日期'],'癌症细胞含量',s['肿瘤细胞含量'])
>         table.add_hline(1,4)
>         table.add_row('病理诊断',s['病理诊断'],'','')
>         table.add_hline(1,4)
> doc.generate_pdf('full',compiler='xelatex', clean_tex=False)
> ```
> 
> gene_pdf()

This is my solution as an extension for pylatex
https://github.com/Freakwill/pylatex_ext 这是我的解决方案，欢饮使用。
中文要用xelatex编译的！

**Comment by JelteF** [comment]
This should allow you to compile with `latexmk` and `xelatex` together:
```python
doc.generate_pdf(compiler='latexmk', compiler_args=['-xelatex'])
```
