### ISSUE TITLE
Readme Links to documentation dont work

### ISSUE THREAD

**Issue by Cornelius2121** [JelteF/PyLaTeX#286]
The links in the readme file to the latest documentation take you to a page that doesn't exist, how can the documentation be accessed?

**Comment by JelteF** [comment]
The links and badges in the readme work fine for me. Maybe hosting had an issue. If you still have this issue, can you post the non working link in a comment?

**Comment by Cornelius2121** [comment]
Hi,

For example when I click on the top link:

"The one generated for the last stable release."

I get redirected to the following route: 
https://jeltef.github.io/PyLaTeX/current/

This route doesnt show anything with a site not found error.

**Comment by JelteF** [comment]
For me that link "just works". So I think this is something related to your internet.
