### ISSUE TITLE
LaTeX snippets without a document

### ISSUE THREAD

**Issue by leventelist** [JelteF/PyLaTeX#287]
Can I use this library to create LaTeX code snippets without creating a full document? If so, how?

**Comment by JelteF** [comment]
Yes you can use the [`dumps`](https://jeltef.github.io/PyLaTeX/current/pylatex/pylatex.base_classes.latex_object.html#pylatex.base_classes.latex_object.LatexObject.dumps) or [`dump`](https://jeltef.github.io/PyLaTeX/current/pylatex/pylatex.base_classes.latex_object.html#pylatex.base_classes.latex_object.LatexObject.dump) method for that. Every class has it.

**Comment by leventelist** [comment]
Thanks!
