### ISSUE TITLE
Remove dependency on nose (port to pytest)

### ISSUE THREAD

**Issue by mcepl** [JelteF/PyLaTeX#294]
I am a maintainer of Python packages in openSUSE, and I am on my crusade of eliminating nose1 from our distribution. When I look at its repository on https://github.com/nose-devs/nose, the last release 1.3.7 was on 2 Jun 2015, and even the last commit on the master branch was on 4 Mar 2016.

[This patch](https://github.com/JelteF/PyLaTeX/files/5014266/denose.patch.txt) eliminates dependency on nose, which has been unnecessary for a long time. Resulting test suite depends on pytest, which is currently perfectly developed and maintained.

**Comment by JelteF** [comment]
Thanks for the patch! Can you create a PR with this change instead? That makes it much easier to merge it in and review it.

**Comment by mcepl** [comment]
> Thanks for the patch! Can you create a PR with this change instead? That makes it much easier to merge it in and review it.

Sorry, I would rather not, I manage around thousand Python packages in \*SUSE, I would drown if making clones for all of them. Sorry.

**Comment by mcepl** [comment]
OK, I gave in. Oh, well.
