### ISSUE TITLE
Can I use PyLaTeX to get the grammar tree of a LaTeX maths formula?

### ISSUE THREAD

**Issue by songyuc** [JelteF/PyLaTeX#298]
Hi, guys,
It is natural that the maths formula may produce the identical output with different expressions, and I need to normalize them so that the different expressions would be normalized into a same LaTeX expression.
My question is can I use PyLaTeX to get the grammar tree of a LaTeX maths formula, so as to normalize the formula by output the tree in a certain way？

Your answer and idea will be appreciated!

**Comment by JelteF** [comment]
Nope, this lib only does generation of latex, not parsing of latex.
