### ISSUE TITLE
TextWrapping in Tabular/Tabularx

### ISSUE THREAD

**Issue by som-shekhar** [JelteF/PyLaTeX#300]
Hi,
I am trying to  wrap the data in the cell  column  and tried lot of ways as suggested in tex exchange using MultiRow,MultiColumn etc, but I am not able to achieve it.
Can you please guide?
![image](https://user-images.githubusercontent.com/5188091/92794310-1644fd80-f3e2-11ea-9e8f-467e0b60a6b9.png)

Also is there any elegant way of handling for more number of columns? As you see in the above screeshot, the last column has gone out of the page.

**Comment by JelteF** [comment]
My advice is to first try to get it working in plain LaTeX, and then convert that to PyLaTeX code.

**Comment by som-shekhar** [comment]
Well there are two things which I found:
1. The word must start with space or else latex won't hyphenate as it considered as paragraph.
2. if the word has dot, then again hyphenation is done.

Any workarounds if the word has dot like in hostnames?
