### ISSUE TITLE
Matplotlib example not working

### ISSUE THREAD

**Issue by raulmd** [JelteF/PyLaTeX#302]
Most likelly is a problem with my setup, but when running that example 
[Example](https://jeltef.github.io/PyLaTeX/current/examples/matplotlib_ex.html)

Result:
`LaTeX Warning: File `C:/Users/User/AppData/Local/Temp/{pylatex-tmp.45dxkgof/5131bfa5-603e-4fee-9366-f8aa72977fb0}.pdf' not found `

It seems as if matplotlib is supposed to generate a pdf with the chart to later be integrated in the document, but it is never created. How could I troubleshoot it?

**Comment by zthurman** [comment]
@raulmd Some environment information would help troubleshoot. For instance I just forked the repo to the following environment:
```
    OS: Manjaro Linux
    Python version: 3.8 (inside venv with dependencies installed from dev-requirements.txt at PyLaTeX root)
```

and was able to run the linked example. It generates two tex files and two pdfs. Things to note about the generated tex files graphic links:

`\includegraphics[width=1\textwidth]{/tmp/pylatex-tmp._qgxb6dd/90e0d245-8cc1-435d-b915-a26db5e0b4f9.pdf}%`

The included graphics look to be stored in a temp directory. Which look like they come from pylatex.utils.make_temp_dir:

```
def make_temp_dir():
    """Create a temporary directory if it doesn't exist.

    Returns
    -------
    str
        The absolute filepath to the created temporary directory.

    Examples
    --------
    >>> make_temp_dir()
    '/var/folders/g9/ct5f3_r52c37rbls5_9nc_qc0000gn/T/pylatex'
    """

    global _tmp_path
    if not _tmp_path:
        _tmp_path = tempfile.mkdtemp(prefix="pylatex-tmp.")
    return _tmp_path
```

Which references [tempfile.mkdtemp](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp). Based on your the path of your latex warning it looks like you're running this on Windows is that correct?

**Comment by raulmd** [comment]
@zthurman  Correct, I am running it on W10.

It is generating several files (more than 2)
```
matplotlib_ex-dpi.aux
matplotlib_ex-dpi.fdb_latexmk
matplotlib_ex-dpi.fls
matplotlib_ex-dpi.log
matplotlib_ex-dpi.pdf
matplotlib_ex-dpi.synctex.gz
matplotlib_ex-dpi.tex
```

Comparing your /includegraphics with mine I see the difference:
Yours:
`\includegraphics[width=1\textwidth]{/tmp/pylatex-tmp._qgxb6dd/90e0d245-8cc1-435d-b915-a26db5e0b4f9.pdf}%`
Mine:
`\includegraphics[width=1\textwidth]{C:/Users/User/AppData/Local/Temp/{pylatex-tmp.8ovs18g0/9bfb4b9d-27c1-416c-a111-3935902b95d5}.pdf}%`

The pdf file with the graphic exist in that folder, but the problem seems to be caused by the filename being enclosed by {  }

If I edit the tex file removing that, I can manually build the tex file successfully.
`\includegraphics[width=1\textwidth]{C:/Users/User/AppData/Local/Temp/pylatex-tmp.8ovs18g0/9bfb4b9d-27c1-416c-a111-3935902b95d5.pdf}%`

Looking at pylatex/utils.py.fix_filename(path), is is possible that this line is worng?
`path_parts = path.split('/' if os.name == 'posix' else '\\')`

```
>>> import os
>>> os.name
'nt'
>>> import platform
>>> platform.platform()
'Windows-10-10.0.18362-SP0'
>>> os. getcwd()
'E:\pylatex\matplotlib example'
```

**Comment by zthurman** [comment]
Given the second paragraph of the [support](https://jeltef.github.io/PyLaTeX/current/#support) section of the docs I think we're a bit off in the weeds here for coming up with our own pretty fix and pull request. It does look like some related issues could be #147, #149, #177.

I just got it going on my Windows 10, I changed the if statement in fix_filename on line 133 of pylatex.utils.py to:
```
if len(file_parts) > 2:
        if os.name == 'posix':
            filename = '{' + '.'.join(file_parts[0:-1]) + '}.' + file_parts[-1]
        else:
            filename = '.'.join(file_parts[0:-1]) + '.' + file_parts[-1]
```
It works on my side, @raulmd can you try the same and see if that behaves on your side as well?

I'll try that on my Manjaro and see if it borks everything over there or not. Testall.sh didn't yell at me when I ran it.

**Comment by zthurman** [comment]
Seems to work over here on Manjaro as well. Testall.sh says that 43 passed with 3 warnings.

@JelteF if the above works for @raulmd as well, is this an acceptable change for me to send over as a pull request?

**Comment by JelteF** [comment]
Yes, please make a PR if it fixes an issue on Windows. If it doesn't break
Linux and looks sane I'll likely merge it.

**Comment by raulmd** [comment]
@zthurman Yes, this solution works, however it does not pass the tests  test_two_dots(): from [here](https://github.com/JelteF/PyLaTeX/blob/master/tests/test_utils_fix_filename.py) No curly braces.

But tried directly with miketex, there is no problem with file names with more than one dot. This is fine
\includegraphics[width=1\textwidth]{C:/Users/User/AppData/Local/Temp/pylatex-tmp.yzh_24aj/foo.bar.pdf}%

File name with dot enclosed in curly braces will not work.
\includegraphics[width=1\textwidth]{C:/Users/User/AppData/Local/Temp/pylatex-tmp.yzh_24aj/{foo.bar}.pdf}%

So I guess your solution for win, works.
