### ISSUE TITLE
Set miktex folder path

### ISSUE THREAD

**Issue by melandur** [JelteF/PyLaTeX#308]
Hi!
Is there a way to set the path to the miktex folder manually, instead of using the environment variables.
This would allow me to drop the miktex into the py2exe build folder and set the path in the code.
Therefore, I could ship the miktex direct with the code. 

Thanks in advanced!

**Comment by JelteF** [comment]
I guess you can give a path to the "compiler" parameter of generate_pdf

**Comment by melandur** [comment]
Thanks for the fast response.
One possible solution for windows:
Set the evironment variable at the beginning of the code.
os.environ['path'] =  'C:\your_path\miktex\miktex\bin\x64'

**Comment by catauggie** [comment]
but if I want to compile through TexStudio, what path should I create?
