### ISSUE TITLE
how to NoEscape for `\input` commnd

### ISSUE THREAD

**Issue by yangdaweihit** [JelteF/PyLaTeX#309]
In the case that there is a tex file to be input like:
```
% test.tex
This is the content of \LaTeX{}
```

I want to input it into a file generated by pylatex:
```
doc = Document()
doc.append(Command('input','test.tex'))
```

While I got the result:
```
This is the content of \textbackslash{}LaTeX\{\}\newline%
```

How could I got the original texts of `test.tex`? Please guide me. Thank you.

My current solution is like:
```
with open('sec1.tex') as infile:
    for line in infile:
        doc.append(NoEscape(line))
```

**ADVISE**:

Add a function `Document.inputfile(file, bNoEscape=True)` to faciliate input original tex file.

**Comment by RaulLima2** [comment]
Hi, have you try put `doc.append(Command('include', 'text'))` ?
