### ISSUE TITLE
Generating table of contents using pylatex

### ISSUE THREAD

**Issue by Mascha16** [JelteF/PyLaTeX#311]
Hello,
I am using pylatex to generate a pdf file and I need to know how to generate the table of contents. Does anyone have an idea about it? 
Thank you.

**Comment by JelteF** [comment]
`Command('tableofcontents')` and install `latexmk`

**Comment by Veliion** [comment]
Hello @JelteF,

I am trying the command you have provided but my .tex file does not contain the \\tableofcontents that is needed. Here is a snippet of my code

`class Report:

    @staticmethod
    def create_report(hosts, args):
        global arguments
        arguments = args

        Command('tableofcontents')

        for host in hosts:
            # Create a section for each host
            with doc.create(Section(host.ip + ": " + str(host.name))):

....

doc.generate_pdf(arguments[2], clean_tex=False, compiler='latexmk', compiler_args=['-f', '-xelatex', '-interaction=nonstopmode'])
`

I have no idea where I might be going wrong. Your help will be greatly appreciated.
