### ISSUE TITLE
Indexing and exponents in Math environment

### ISSUE THREAD

**Issue by joonas-si** [JelteF/PyLaTeX#319]
Hi there,

I am trying to use pylatex to create an output file for a calibration. In this I like to write equations.
But if I try to index my Variables like " T_0" or "T_{0}" pylatex automatically inserts a backslash before the underscore and LaTex doesn't interprets it as index.
Another problem I came across are exponents. If I try to write "x^2" or x^{2} pylatex again inserts a backslash and an error is thrown, saying that I should use /mathaccent if I want to use accents.
Can you tell me what I am doing wrong?

Thank you so much!
PS: The package is very nice!!

**Comment by kai-arsenault** [comment]
Hi was there any solution to this. I am running into the same problem.
