### ISSUE TITLE
"-", "--" and "---" are not escaped

### ISSUE THREAD

**Issue by rutsky** [JelteF/PyLaTeX#33]
In LaTeX `-`, `--` and `---` are commands for hyphen, en-dash and em-dash correspondingly.
Currently these characters are not escaped.

If you think that such behavior is a feature, I think it should be documented.

**Comment by JelteF** [comment]
No, it is probably better if they would just become 1, 2 and 3 hyphens correspondingly. Haven't had this issue myself since it doesn't really fuck with the document structure which is why I made the escape function in the first place. You could add it to your other pull request if you want.

**Comment by rutsky** [comment]
What do you suggest as the replacement?

1. `{-}`
2. `\textendash`
3. `\textemdash`

**Comment by JelteF** [comment]
I think `{-}` would be best, since it is most likely what the user wanted.

**Comment by rutsky** [comment]
I pushed fix in PR #34.

**Comment by artel1992** [comment]
When I try add this in preamble:
```python
doc.preamble.append(Command('usepackage', arguments='pdfx', options='mathxmp, a-1a'))
```
or 
```python
doc.preamble.append(NoEscape(r'\usepackage[mathxmp, a-1a]{pdfx}'))
```
the result is like this 
```latex
\usepackage[mathxmp, a{-}1a]{pdfx}%%
```

**Comment by shaiquie-zieye** [comment]
Yes, @artel1992 is right, IHMO it shouldn't work like that. What do you think @JelteF?

**Comment by JelteF** [comment]
I agree feel free to fix it.
