### ISSUE TITLE
column width failure

### ISSUE THREAD

**Issue by petaflot** [JelteF/PyLaTeX#332]
following the complex_report example with a few minor modifications, this doesn't work:
```python
         # Add document title
         with first_page.create(Head("R")) as right_header:
             # Add cheque images
             with right_header.create(Tabu("[50pt]X[c] X[c] X[c] X[c]",width=4)) as cheque_table:
                 cheque_file = os.path.join(os.path.dirname(__file__), 'kitten.png')
                 cheque = StandAloneGraphic(cheque_file, image_options="width=50px")
                 cheque_table.add_row([cheque, cheque,cheque,cheque])
                 #cheque_table.add_row(['',cheque, cheque])
```
the table is shot at the extreme right of the page, and there's an additional 't' added before the last kitten

this produces more or less the expected result (units have been removed, but there is still some space between each cell)
```python
         # Add document title
         with first_page.create(Head("R")) as right_header:
             # Add cheque images
             with right_header.create(Tabu("[50]X[c] X[c] X[c] X[c]",width=4)) as cheque_table:
                 cheque_file = os.path.join(os.path.dirname(__file__), 'kitten.png')
                 cheque = StandAloneGraphic(cheque_file, image_options="width=50px")
                 cheque_table.add_row([cheque, cheque,cheque,cheque])
                 #cheque_table.add_row(['',cheque, cheque])
```
BUT I get 
```subprocess.CalledProcessError: Command '['pdflatex', '--interaction=nonstopmode', '/mnt/naspi/naspi/metameta/meta/invoice.tex']' returned non-zero exit status 1.```

**Comment by JelteF** [comment]
Check the resulting `invoice.tex` and compile it using latex manually. That should show the probem. Probably you're missing a `NoEscape` somewhere.
