### ISSUE TITLE
add_row() should be add_column()

### ISSUE THREAD

**Issue by petaflot** [JelteF/PyLaTeX#333]
look at the "Complex report" example:

line 63 says

```python
footer_table.add_row([branch_address, branch_address,
```

when it should be

```python
footer_table.add_column([branch_address, branch_address,
```

This is confusing.

**Comment by JelteF** [comment]
No, it's not. The same address is 3 times in the same row. You can see this in the outputted picture of the document.

**Comment by petaflot** [comment]
my bad here :-/
