### ISSUE TITLE
No LaTex compiler was found (Windows 10)

### ISSUE THREAD

**Issue by catauggie** [JelteF/PyLaTeX#361]
Hello. 

Try to compile basic example using PyLaTex. But the same error:
CompilerError: No LaTex compiler was found
Either specify a LaTex compiler or make sure you have latexmk or pdfLaTex installed.

Everywhere solutions for Linux. Please, help for windows 10.

**Comment by ChristianKleineidam** [comment]
Install a LaTeX compiler like https://miktex.org/

**Comment by catauggie** [comment]
> Install a LaTeX compiler like https://miktex.org/

I have already installed it and I don't have idea why it doesn't work

**Comment by ChristianKleineidam** [comment]
Is it in your path?

**Comment by catauggie** [comment]
I have already added a folder to path, but maybe not that. 
It should contains miktex.exe?

**Comment by catauggie** [comment]
> No, it has to contain the compiler you want to use, so latexmk or pdfLaTex.

can you please provide an example of such path?

**Comment by ChristianKleineidam** [comment]
This is a Github issue and you are already abusing it by putting in personal help topic that doesn't really belong here. I don't feel like this is the place to put effort into explaining how to put things into path.

**Comment by JelteF** [comment]
Yes, there's enough answers for this problem on Google/stackoverflow
