### ISSUE TITLE
Add multicol/multirow support for tables.

### ISSUE THREAD

**Issue by vext01** [JelteF/PyLaTeX#4]
It would be sweet if we could use multirow/multicol in tables somehow.

Cheers

**Comment by Rsullivan00** [comment]
I have a solution working at PR #59, using MultiColumn and MultiRow classes, which are added to a table using the 'table.add_row()' interface.

@vext01, your general example is included in the 'multirow' test.

**Comment by JelteF** [comment]
This is fixed by #59
