### ISSUE TITLE
jobname cannot read paths

### ISSUE THREAD

**Issue by Vayel** [JelteF/PyLaTeX#45]
`pdflatex --jobname="/home/eleve/vincent.lefoulon/Documents/MPF/data/prod/filename" "/home/eleve/vincent.lefoulon/Documents/MPF/data/prod/filename.tex"` does not work whereas `pdflatex --jobname="filename" "/home/eleve/vincent.lefoulon/Documents/MPF/data/prod/filename.tex"` does. But the second command saves the file in the working directory.

`pdflatex --output-directory ~/Documents/MPF/data/prod "/home/eleve/vincent.lefoulon/Documents/MPF/data/prod/filename.tex"` would do the job and save the file as `~/Documents/MPF/data/prod/filename.pdf`

**Comment by Vayel** [comment]
`command = compiler + ' --output-directory="' + os.path.dirname(filename) + '" "' + filename + '.tex"'` does the job with pdflatex.

**Comment by Vayel** [comment]
Or maybe using the `cd` command would do the job.

**Comment by jrast** [comment]
I also encountered some problems which might be related to this on a windows system. If I specified the filename as absolute path, the aux file was not found during the `pdflatex` run. My quick fix was this:
```python
cur_path = os.getcwd()
os.chdir(os.path.dirname(filename))
doc.generate_pdf()
os.chdir(cur_path)
```

Maybe something like this should be included in generate_pdf.

**Comment by JelteF** [comment]
This should be fixed now
