### ISSUE TITLE
Specifying where the PDF should reside

### ISSUE THREAD

**Issue by bigoperm** [JelteF/PyLaTeX#46]
How do I specify where the generated PDF file should reside? Adding an argument to the constructor only seems to control where the temporary Latex files get put -- I'd like to specify (also) where the actual PDF files is written.

**Comment by khyox** [comment]
The `filename` option of **generate_pdf** and **generate_tex** is actually a full pathname option, so I use it to specify both where the PDF/TeX output should reside and the file name.

**Comment by JelteF** [comment]
I think #45  is related.

**Comment by JelteF** [comment]
This should be fixed by the same commit as #45
