### ISSUE TITLE
xeLaTeX needed

### ISSUE THREAD

**Issue by speedcell4** [JelteF/PyLaTeX#47]
I can not write in Chinese, cause my Mac need xeLaTeX as compiler.
e.g. 
```python
import pylatex

doc = pylatex.Document(maketitle=True)

with doc.create(pylatex.Section(r'第一节')):
    pass

doc.generate_pdf()
```
this can not generate .pdf successfully, the following code is needed for .tex
```LaTeX
% !TEX program = xelatex
```

**Comment by JelteF** [comment]
You can pass a compiler to generate_pdf

**Comment by speedcell4** [comment]
thank you

**Comment by a-a-GiTHuB-a-a** [comment]
How do you pass the XeLaTeX compiler?
> You can pass a compiler to generate_pdf
