### ISSUE TITLE
 './testall.sh' does not work if the system python version is still 2.*

### ISSUE THREAD

**Issue by votti** [JelteF/PyLaTeX#64]
If the system default python version is still 2.*, the testall.sh script will try to run the 'python2_source' tests, resulting in the test failing as the folder does not exist.

I propose to add an optional command line argument, which allows to indicate the python command to be used. This will also allow the user to test everything under different python versions,.
e.g. ./testall.sh -p python3

**Comment by JelteF** [comment]
This is fixed now
