### ISSUE TITLE
Possible way to add pylatex in to Scribus CLI workflow

### ISSUE THREAD

**Issue by luzpaz** [JelteF/PyLaTeX#67]
Just making a notation here. The Scribus CLI is still under development ATM but it would seem advantageous to hook in pyLaTex as a way to satisfy different needs.

**Comment by JelteF** [comment]
I have never used Scribus, so I haven't got a clue what you mean exactly. If you are going to make a pull request for this could you let me know what you plan on doing, I might be able to help out a bit.

**Comment by JelteF** [comment]
I will close this issue since I do not understand why it is needed in this repository.
