### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by JelteF** [JelteF/PyLaTeX#7]
Currently the only documentation are the examples. This should be changed.

**Comment by Vayel** [comment]
Adding the PDF files generated by the examples should help.

**Comment by kv-kunalvyas** [comment]
In addition to the generated PDF files, a markdown file containing all present functions and their parameters, type and return values can be made. However, I don't have an idea of how big would it become this way.

**Comment by JelteF** [comment]
I'm planning on learning how to set up sphinx documentation this summer. That way the docstrings in the code will be converted to documentation automatically.

**Comment by rfilmyer** [comment]
Okay. So I added stuff for the "Library Usage" section, but are there any other big things that you need help working on documentation-wise?

**Comment by JelteF** [comment]
All that's left is basically adding semi useful docstrings for everything. And moving the contributing instructions to the actual documentation, and add stuff about how the documentation works to it. 

If you want to write docstrings, use the numpy format since those are actually useful. See this for explanation. http://sphinx-doc.org/latest/ext/napoleon.html

And you can make html in the docs directory to generate the actual documentation.

**Comment by JelteF** [comment]
I'll write the contributing stuff myself btw

**Comment by rfilmyer** [comment]
Question: Why do Arguments and Options exist if they're just Parameters with an extra boolean flag put on?

**Comment by JelteF** [comment]
Good question. I wanted to change that. Forgot about that.

**Comment by sebastianhaas** [comment]
I guess there are a few situations where having Options and Parameters could be of use. E.g. last month, I needed my options/arguments to be in a certain order.
I'm not saying that can't be done with more primitive parameters, but I'd rather take a look on all possible usages of arguments and options in the latex ecosystem and then make the decision.
Cheers
On Aug 21, 2015 9:19 AM, Jelte Fennema <notifications@github.com> wrote:Good question. I wanted to change that. Forgot about that.

**Comment by JelteF** [comment]
I do want to keep Options and Arguments, but the logic that handles them should be changed. The differences are currently handled in the Parameters class and I want to move that to the actual Options and Arguments classes.

**Comment by JelteF** [comment]
I have just pushed a change that removes the optional boolean and handles it in a different and cleaner way.

**Comment by JelteF** [comment]
I am going to close this issue and make a couple of new issues that split this up.
