### ISSUE TITLE
BaseLaTeXNamedContainer not supporting multiple arguments

### ISSUE THREAD

**Issue by sebastianhaas** [JelteF/PyLaTeX#71]
Is there a reason `BaseLaTeXNamedContainer ` is currently only supporting a single argument?

According to this, environments can have up to 9 parameters:
http://www.emerson.emory.edu/services/latex/latex_19.html

I'm happy to provide a patch if this is unintentional.

**Comment by JelteF** [comment]
I haven't run into an issue with this yet, but I see what you mean. If you write a patch, please use the Options and Argument classes to do so. https://github.com/JelteF/PyLaTeX/blob/master/pylatex/parameters.py

I am planning on refactoring a lot of the codebase this summer anyway, so this would probably have come up. But I always appreciate patches.

**Comment by sebastianhaas** [comment]
I will. I somehow introduced them with my last request.

Getting testall.sh to run is quite a pain right now. Already took me >1h. Would you be interested in a vagrant configuration? I'm halfway there, so I guess I could provide the Vagrantfile once I'm finished.

**Comment by JelteF** [comment]
Is it really that hard? I'm currently working on the documentation, so could you let me know what troubles you ran into?

Have you tried `pip install -e .[all]`? That should install all python requirements, the only thing that is then needed is a recent version of LaTeX. Is that the issue?

**Comment by sebastianhaas** [comment]
I did, but matlabplotlib is not building without the freetype and libpng devel package on ubuntu. It's not that hard, it just takes time figuring everything out correctly.
I suppose for the test script to work properly one has to install pylatex using pip install -e . too?
On Jun 23, 2015 9:25 AM, Jelte Fennema <notifications@github.com> wrote:Is it really that hard? I'm currently working on the documentation, so could you let me know what troubles you ran into?

Have you tried pip install -e .[all]? That should install all python requirements, the only thing that is then needed is a recent version of LaTeX. Is that the issue?

**Comment by JelteF** [comment]
Ah, ok. That is what I always dislike about Ubuntu/Debian, that you always need all those devel packages. 

And yeah, you should install it with `pip install -e .` or you can just use `python setup.py` which does the same without a lot of the dependency calculation pip does.

**Comment by JelteF** [comment]
I have just started refactoring (I needed a bit of a break from the documentation writing). The base_classes file has been split up into two different files and the `BaseLaTeXNamedContainer` has been renamed to `Environment`. I'm not sure how good git handles this if you made changes in the base_classes file before this change, so it might be easier to just copy and paste your changes if you already have some.

**Comment by sebastianhaas** [comment]
Well actually the ``BaseLaTexNamedContainer`` is pretty buggy anyway. It only supports a single string as parameter for both arguments and options although the docs explicitly allow either string, list or the respective class instance.

I'll just copy it over anyways. I also did an example on how to use PyLaTeX for custom commands and environments.

**Comment by sebastianhaas** [comment]
So maybe a unit test would be appropriate too, making sure the parameters for as specified, which is not the case at the moment.

**Comment by JelteF** [comment]
I think I remember that I wanted to rewrite `BaseLaTexNamedContainer` when the `Command` class was created, which seemed like a good plan. But I think I ran into issues with circular imports because `Command` used the `BaseLaTeXClass` class which was in the same file. At that point I think I gave up, because I didn't feel like refactoring back then.

**Comment by JelteF** [comment]
I think the new docs will really help finding issues like this btw, since they are more in the open now, instead of only in the code.

**Comment by sebastianhaas** [comment]
Yes, that is apparently an issue. ``Arguments`` and ``Options`` both rely on BaseLatexClass which is in the same module as ``BaseLaTexNamedContainer ``. I currently solved it by doing the import inside ``BaseLaTexNamedContainer ``. Not super elegant but the only way without splitting ``base_classes``.

**Comment by sebastianhaas** [comment]
Take a look if you want
https://github.com/sebastianhaas/PyLaTeX/commit/2c7c285d062a546f3e3bf4d0bfed20fa5c620cac

**Comment by JelteF** [comment]
I wrote down some comments after a quick look. Great that you made an example for extending PyLaTeX btw.

**Comment by sebastianhaas** [comment]
I will try to meet your recommendations asap. Please just drop me a line on your decision regarding splitting the typo fix and the ``arguments`` pluralization in two separate commits. I can clearly see your point there, but of course it implies resetting the commit so if you don't care too much ;)

**Comment by JelteF** [comment]
Closing this because it is fixed
