### ISSUE TITLE
Is pip package up-to-date ?

### ISSUE THREAD

**Issue by matthieu-lapeyre** [JelteF/PyLaTeX#77]
I think the pip package is out of date as the API does not match the documentation. I spent quite a lot of time to find where is the Command and Options classes as they were not in the base_classes module.

https://jeltef.github.io/PyLaTeX/pylatex/pylatex.base_classes.command.html

**Comment by rfilmyer** [comment]
It looks like pip is up to date with the last tagged version, 0.8.0, but I think the author has spent a bunch of time refactoring and creating new documentation since then.

**Comment by JelteF** [comment]
@rfilmyer is right. The master branch is not the version that is currently in pip. That is the 0.8.0 release (which is currently about sixty commits behind master). To look at the library layout for that release, take a look at https://github.com/JelteF/PyLaTeX/tree/v0.8.0, keep in mind that almost no documentation was written back then and only the examples and the docstrings might help you out a bit.

**Comment by JelteF** [comment]
Closing this
