### ISSUE TITLE
No docs on how the Vagrantfile works

### ISSUE THREAD

**Issue by JelteF** [JelteF/PyLaTeX#80]
@sebastianhaas Could you write something on how to use this?

**Comment by sebastianhaas** [comment]
Yes, of course. I'll write a few lines next week. Thanks for merging!
On Aug 18, 2015 1:46 AM, Jelte Fennema <notifications@github.com> wrote:@sebastianhaas Could you write something on how to use this?

**Comment by sebastianhaas** [comment]
Hey! Next week became two weeks. Sorry for that.

Where would you like the Vagrant section? Maybe as a subsection in "How to contribute"?

Cheers

**Comment by sebastianhaas** [comment]
Although this might be of more general interest as it also simplifies the process of setting up a working LaTeX environment.

Maybe a subsection in "Library usage"?

**Comment by sebastianhaas** [comment]
Aaah nvm. It's probably more suitable for people who want to contribute on PyLaTeX itself. I'll add it under "How to contribute" for now.

**Comment by JelteF** [comment]
Yeah, in contributing seems like the right place.

**Comment by JelteF** [comment]
Fixed by #89
