### ISSUE TITLE
Replace Sphinx style docstrings for Numpy style.

### ISSUE THREAD

**Issue by JelteF** [JelteF/PyLaTeX#83]
Numpy style docstrings are much more readable when reading the actual source code. It is important that this is consistantly used everywhere.

**Comment by rfilmyer** [comment]
I'm on pacific time, so I'll work on some docstrings this evening and let you know where I stand at the end of day today (ie morning CET)

**Comment by JelteF** [comment]
Thanks, sounds great. I might work on some stuff tomorrow evening (CET),
but I'll be on a holiday the week after that so I might not respond
(quickly) then.

**Comment by rfilmyer** [comment]
It's an open source project, don't kill yourself working on it too hard :p

**Comment by JelteF** [comment]
Don't worry. I don't work on this to much.

**Comment by rfilmyer** [comment]
Started off with `utils.py`, finished on my fork.

**Comment by JelteF** [comment]
I merged your changes in with some small changes.

**Comment by JelteF** [comment]
All docstrings have been converted.
